before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
script:
  - npm run lint
  - npm test

